### ISSUE TITLE
[bug]: Asterisk fails to compile following commit 71a2e8c on Ubuntu 20.04

### ISSUE THREAD

**Issue by iueoa** [asterisk/asterisk#1058]
### Severity

Major

### Versions

21

### Components/Modules

pjproject

### Operating Environment

Ubuntu 20.04 LTS, gcc version 10.5.0 (Ubuntu 10.5.0-1ubuntu1~20.04) 

### Frequency of Occurrence

None

### Issue Description

Following commit 71a2e8c (https://github.com/asterisk/asterisk/commit/71a2e8c5998a1520ddc1ea2756c61c611a0d419e), Asterisk no longer compiles in Ubuntu 20.04

### Relevant log output

```shell
In file included from /root/src/asterisk/include/asterisk/lock.h:63,                                                                                            
                 from /root/src/asterisk/include/asterisk/vector.h:22,          
                 from /root/src/asterisk/include/asterisk/stringfields.h:178,
                 from /root/src/asterisk/include/asterisk/res_pjsip.h:30,    
                 from res_pjsip_authenticator_digest.c:23:                  
res_pjsip_authenticator_digest.c: In function 'verify':                                                                                                         
res_pjsip_authenticator_digest.c:471:38: error: expected expression before 'pj_status_t'                                                                        
  471 |  authed = SCOPE_CALL_WITH_RESULT(-1, pj_status_t, pjsip_auth_srv_verify, &auth_server, rdata, &response_code);                                          
      |                                      ^~~~~~~~~~~                                                                                                        
/root/src/asterisk/include/asterisk/logger.h:1018:2: note: in definition of macro 'SCOPE_CALL_WITH_RESULT'                                                      
 1018 |  __var = __funcname(__VA_ARGS__)                                                                                                                        
      |  ^~~~~                                                                  
res_pjsip_authenticator_digest.c:442:6: warning: unused variable 'response_code' [-Wunused-variable]                                                            
  442 |  int response_code;                                                                                                                                     
      |      ^~~~~~~~~~~~~                                                      
res_pjsip_authenticator_digest.c: In function 'digest_check_auth':                                                                                              
res_pjsip_authenticator_digest.c:636:4: error: expected ';' before 'verify_res' 
  636 |    verify_res[idx] = AUTH_NOAUTH;                                       
      |    ^~~~~~~~~~                                                           
In file included from /root/src/asterisk/include/asterisk/lock.h:63,       
                 from /root/src/asterisk/include/asterisk/vector.h:22,                                                                                          
                 from /root/src/asterisk/include/asterisk/stringfields.h:178,
                 from /root/src/asterisk/include/asterisk/res_pjsip.h:30,    
                 from res_pjsip_authenticator_digest.c:23:                    
res_pjsip_authenticator_digest.c:638:49: error: expected expression before 'int'
  638 |    verify_res[idx] = SCOPE_CALL_WITH_RESULT(-1, int, verify, endpoint_id, auth, rdata, tdata->pool);
      |                                                 ^~~                                                                                                     
/root/src/asterisk/include/asterisk/logger.h:1018:2: note: in definition of macro 'SCOPE_CALL_WITH_RESULT'                                                      
 1018 |  __var = __funcname(__VA_ARGS__)                                                                                                                        
      |  ^~~~~                                                                                                                                                  
At top level:                                                                   
res_pjsip_authenticator_digest.c:435:12: warning: 'verify' defined but not used [-Wunused-function]                                                             
  435 | static int verify(const char *endpoint_id, const struct ast_sip_auth *auth,                                                                             
      |            ^~~~~~                                                                                                                                       
make[1]: *** [/root/src/asterisk/Makefile.rules:165: res_pjsip_authenticator_digest.o] Error 1                                                                  
make[1]: *** Waiting for unfinished jobs....                                                                                                                    
make: *** [Makefile:396: res] Error 2                                           
CC="cc" CXX="g++" LD="" AR="" RANLIB="" CFLAGS="" LDFLAGS="" make -C menuselect CONFIGURE_SILENT="--silent" makeopts
```

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by michaelnugent** [comment]
This macro in include/asterisk/logger.h is missing a semi-colon on the second ast_trace (added below).
#define SCOPE_CALL_WITH_RESULT(level, __type, __funcname, ...) \
({ \
        __type __var; \
        ast_trace(level, "--> Calling %s\n", #__funcname); \
        __var = __funcname(__VA_ARGS__); \
        ast_trace(level, "<-- Return from %s\n", #__funcname); \
        __var; \
})

Make sure you compile with gnu extensions or this macro gives some issues.

**Comment by gtjoseph** [comment]
@michaelnugent Exactly what ./configure and make command lines are you using that reproduces the issue?

**Comment by Maurotb** [comment]
same problem with debian 12, semi-colon added. 
Build with simple
./configure
make
