### ISSUE TITLE
[bug]: app_voicemail imap compile errors

### ISSUE THREAD

**Issue by mbradeen** [asterisk/asterisk#174]
### Severity

Trivial

### Versions

master

### Components/Modules

app_voicemail

### Operating Environment

Ubuntu 20.04

### Frequency of Occurrence

None

### Issue Description

Two compile errors, one caused by #163.

```app_voicemail_imap.c: In function ‘messagecount’:
app_voicemail_imap.c:2601:9: error: ISO C90 forbids mixed declarations and code [-Werror=declaration-after-statement]
 2601 |         int count;
      |         ^~~
app_voicemail_imap.c: In function ‘msg_create_from_file’:
app_voicemail_imap.c:6193:15: error: unused variable ‘fmt’ [-Werror=unused-variable]
 6193 |         char *fmt = ast_strdupa(recdata->recording_ext);
      |               ^~~
cc1: all warnings being treated as errors

```

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines
