### PR TITLE
pjproject: Fix srtp build failure on OpenSSL < 1.1.0

### LINKED ISSUE #1899: [bug]: Bundled pjproject 2.17 fails to build on OpenSSL < 1.1.0: undefined reference to EVP_CIPHER_CTX_reset, HMAC_CTX_new, HMAC_CTX_free
### Severity

Major

### Versions

20.20.

### Components/Modules

pjsip project

### Operating Environment

centos 7 

### Frequency of Occurrence

Constant

## Summary
Building Asterisk with bundled pjproject 2.17 fails on systems with 
OpenSSL < 1.1.0 (e.g. CentOS 7 with OpenSSL 1.0.2k).

## Error
collect2: error: ld returned 1 exit status

aes_icm_ossl.c:(.text+0x237): undefined reference to `EVP_CIPHER_CTX_reset'
aes_gcm_ossl.c:(.text+0x156): undefined reference to `EVP_CIPHER_CTX_reset'
hmac_ossl.c:(.text+0xe8): undefined reference to `HMAC_CTX_free'
hmac_ossl.c:(.text+0x2f3): undefined reference to `HMAC_CTX_new'

## Cause
The bundled libsrtp in pjproject 2.17 uses OpenSSL 1.1+ APIs without 
version guards in:
- third_party/srtp/crypto/cipher/aes_gcm_ossl.c
- third_party/srtp/crypto/cipher/aes_icm_ossl.c
- third_party/srtp/crypto/hash/hmac_ossl.c

## Environment
- OS: CentOS 7
- OpenSSL: 1.0.2k
- Asterisk version: <your version>
- pjproject: bundled 2.17

## Fix
Upstream fix submitted to pjproject: pjsip/pjproject#4945

### Relevant log output

```shell

```

### Asterisk Issue Guidelines

- [x] Yes, I have read the Asterisk Issue Guidelines

### LINKED ISSUE #4945: Build failure on OpenSSL 1.0.x: undefined reference to EVP_CIPHER_CTX_reset, HMAC_CTX_new, HMAC_CTX_free
### Describe the bug

Building PJSIP 2.17 fails at link stage when OpenSSL 1.0.x is present on the system. The bundled libsrtp uses OpenSSL 1.1+ APIs (EVP_CIPHER_CTX_reset, HMAC_CTX_new, HMAC_CTX_free) without version guards, causing undefined reference errors.

### Steps to reproduce

On a system with OpenSSL 1.0.x installed, download PJSIP 2.17
Run ./configure
Run make dep && make
Build fails at linking pjmedia-test

### PJSIP version

2.17

### Context

Platform: Linux x86_64
OS: CentOS/RHEL 7 with OpenSSL 1.0.x
Build system: GCC, GNU Make

### Log, call stack, etc

```shell
aes_icm_ossl.c:(.text+0x237): undefined reference to `EVP_CIPHER_CTX_reset'
aes_gcm_ossl.c:(.text+0x156): undefined reference to `EVP_CIPHER_CTX_reset'
hmac_ossl.c:(.text+0xe8): undefined reference to `HMAC_CTX_free'
hmac_ossl.c:(.text+0x2f3): undefined reference to `HMAC_CTX_new'
collect2: error: ld returned 1 exit status
```

### PR DESCRIPTION
**Pull request by phoneben**
pjproject: Fix srtp build failure on OpenSSL < 1.1.0

Adds a patch for bundled pjproject to fix build failure when compiling against OpenSSL < 1.1.0 (e.g. OpenSSL 1.0.2k on CentOS 7).

Three symbols introduced in OpenSSL 1.1.x were called unconditionally in libsrtp without version guards:

- `EVP_CIPHER_CTX_reset()` in aes_gcm_ossl.c and aes_icm_ossl.c, now guarded and falling back to EVP_CIPHER_CTX_cleanup() + EVP_CIPHER_CTX_init() on older OpenSSL and LibreSSL.

- `HMAC_CTX_new()`/`HMAC_CTX_free()` in hmac_ossl.c, now guarded and falling back to stack-allocated HMAC_CTX with HMAC_CTX_init()/ HMAC_CTX_cleanup() on older OpenSSL and LibreSSL.

Upstream fix: pjsip/pjproject#4945

Resolves: #1899

### CODE REVIEW

**Comment by phoneben** [comment]
cherry-pick-to: 20
cherry-pick-to: 22
cherry-pick-to: 23

**Comment by phoneben** [comment]
this can go in only after https://github.com/asterisk/asterisk/pull/1889 is merged !

setting  this a draft till then

**Review by gtjoseph — CHANGES_REQUESTED** [review]
The Asterisk build process disables pjproject's third-party/libsrtp so this doesn't apply to us.  To confirm, I just built Asterisk on CentOS 7 with OpenSSL 1.0.2k and pjproject 2.17 and it built fine.

Did you actually try an Asterisk build?
