### ISSUE TITLE
[bug]: Bundled pjproject 2.17 fails to build on OpenSSL < 1.1.0: undefined reference to EVP_CIPHER_CTX_reset, HMAC_CTX_new, HMAC_CTX_free

### ISSUE THREAD

**Issue by phoneben** [asterisk/asterisk#1899]
### Severity

Major

### Versions

20.20.

### Components/Modules

pjsip project

### Operating Environment

centos 7 

### Frequency of Occurrence

Constant

## Summary
Building Asterisk with bundled pjproject 2.17 fails on systems with 
OpenSSL < 1.1.0 (e.g. CentOS 7 with OpenSSL 1.0.2k).

## Error
collect2: error: ld returned 1 exit status

aes_icm_ossl.c:(.text+0x237): undefined reference to `EVP_CIPHER_CTX_reset'
aes_gcm_ossl.c:(.text+0x156): undefined reference to `EVP_CIPHER_CTX_reset'
hmac_ossl.c:(.text+0xe8): undefined reference to `HMAC_CTX_free'
hmac_ossl.c:(.text+0x2f3): undefined reference to `HMAC_CTX_new'

## Cause
The bundled libsrtp in pjproject 2.17 uses OpenSSL 1.1+ APIs without 
version guards in:
- third_party/srtp/crypto/cipher/aes_gcm_ossl.c
- third_party/srtp/crypto/cipher/aes_icm_ossl.c
- third_party/srtp/crypto/hash/hmac_ossl.c

## Environment
- OS: CentOS 7
- OpenSSL: 1.0.2k
- Asterisk version: <your version>
- pjproject: bundled 2.17

## Fix
Upstream fix submitted to pjproject: pjsip/pjproject#4945

### Relevant log output

```shell

```

### Asterisk Issue Guidelines

- [x] Yes, I have read the Asterisk Issue Guidelines

**Comment by phoneben** [comment]
this can go in only after https://github.com/asterisk/asterisk/pull/1889 is merged !

setting this a draft till then

**Comment by gtjoseph** [comment]
As noted in the PR, I just tried this myself and it builds fine.  We don't use pjproject's third-party/libsrtp.  Building pjproject standalone may fail but are you sure this fails when building Asterisk?

**Comment by phoneben** [comment]
no i did not try to use asterisk i just looked at asterisk and saw the files are there. 
so tested standalone .
since i had a hard time figuring out why asterisk did not build 2.16 so 2.17 went directly to source .
if the files are there and not being built iam just going to close  

just doulble checking you built 2.17 not 2.16 correct ?

**Comment by gtjoseph** [comment]
> Just doulble checking you built 2.17 not 2.16 correct ?\

Correct :)
