### PR TITLE
fix: backport pjproject stdatomic.h GCC 4.8 build failure patch

### LINKED ISSUE #1883: [bug]: fix: stdatomic.h false positive on GCC 4.8
### Severity

Critical

### Versions

20.19.0

### Components/Modules

pjsip project

### Operating Environment

centos 7

### Frequency of Occurrence

Constant

### Issue Description

fatal error: stdatomic.h: No such file or directory when building pjproject 2.16 on GCC 4.8. Commit #4570 ("Use C11 atomics when available") introduced a false positive in the C11 atomics detection logic. When building with -std=gnu11, __STDC_VERSION__ >= 201112L evaluates to true on GCC 4.8, causing the build to unconditionally include stdatomic.h — which does not exist in GCC 4.8 (support was added in GCC 4.9).

### Steps to reproduce

Use a system with GCC 4.8 (CentOS 7 / RHEL 7)
Attempt to build pjproject 2.16
Build fails with fatal error: stdatomic.h: No such file or directory

### Context

OS: CentOS 7
GCC: 4.8.5 (Red Hat 4.8.5-44)
pjproject: 2.16
Build flag in use: -std=gnu11
Introduced by: commit #4570 "Use C11 atomics when available"``

### Relevant log output

```shell
../src/pj/os_core_unix.c:52:27: fatal error: stdatomic.h: No such file or directory
 #    include <stdatomic.h>
```

### Asterisk Issue Guidelines

- [x] Yes, I have read the Asterisk Issue Guidelines

### PR DESCRIPTION
**Pull request by phoneben**
pjproject 2.16 (bundled) fails to build on GCC 4.8 (CentOS/RHEL 7) due to a false positive C11 atomics detection introduced in pjproject commit #4570. A fix has been submitted upstream to pjproject (#4933).

Adding a local patch to third-party/pjproject/patches/ until a fixed version of pjproject is bundled in Asterisk.

Fixes build error:
../src/pj/os_core_unix.c:52:27: fatal error: stdatomic.h: No such file or directory

Resolves: #1883

### CODE REVIEW

**Comment by phoneben** [comment]
cherry-pick-to: 20
cherry-pick-to: 22
cherry-pick-to: 23

**Comment by gtjoseph** [comment]
FYI for others... pjsip/pjproject#4933 was merged.

**Comment by phoneben** [comment]
that is why i put it here  also till the next version did i miss something ?

**Comment by gtjoseph** [comment]
> that is why i put it here also till the next version did i miss something ?

Nope.  Before merging to Asterisk, we usually wait for pjproject to merge it so we know it's accepted.  I was just letting others know that they did merge it so we're OK to merge it here.

**Review by gtjoseph — DISMISSED** [review]
The sequence number for the patch filename should be 0060 instead of 0001 per third-party/pjproject/patches/README

**Comment by phoneben** [comment]
is the process of backporting from the pjsip project documented ?

**Comment by gtjoseph** [comment]
> is the process of backporting from the pjsip project documented ?

I _thought_ I created a wiki page describing the `third-party` directory and the process for applying patches and updating versions but I can't seem to find it.  I wonder if it got lost when we moved the documentation from the old Confluence wiki site to the new docs site a few years back.  I'll see if I can find it.

**Review by gtjoseph — APPROVED** [review]

**Review by jcolp — APPROVED** [review]
