### ISSUE TITLE
[bug]: codec_ilbc:  Fails to build with ilbc version 3.0.4

### ISSUE THREAD

**Issue by gtjoseph** [asterisk/asterisk#84]
### Severity

Minor

### Versions

18,20,master

### Components/Modules

codec_ilbc

### Operating Environment

Fedora 37
ilbc-3.0.4-3.fc37.x86_64

### Frequency of Occurrence

Constant

### Issue Description

ilbc 3.0 has api changes that prevent codec_ilbc from building

### Relevant log output

```shell
[CC] codec_ilbc.c -> codec_ilbc.o
codec_ilbc.c: In function ‘lintoilbc_new’:
codec_ilbc.c:79:9: error: implicit declaration of function ‘initEncode’ [-Werror=implicit-function-declaration]
   79 | initEncode(&tmp->enc, mode);
      | ^~~~~~~~~~
codec_ilbc.c: In function ‘ilbctolin_framein’:
codec_ilbc.c:130:17: error: implicit declaration of function ‘initDecode’ [-Werror=implicit-function-declaration]
  130 | initDecode(&tmp->dec, mode, USE_ILBC_ENHANCER);
      | ^~~~~~~~~~
codec_ilbc.c:139:17: error: implicit declaration of function ‘iLBC_decode’ [-Werror=implicit-function-declaration]
  139 | iLBC_decode(tmpf, plc_mode ? f->data.ptr + x : NULL, &tmp->dec, plc_mode);
      | ^~~~~~~~~~~
codec_ilbc.c: In function ‘lintoilbc_frameout’:
codec_ilbc.c:184:17: error: implicit declaration of function ‘iLBC_encode’ [-Werror=implicit-function-declaration]
  184 | iLBC_encode((ilbc_bytes *) pvt->outbuf.BUF_TYPE, tmpf, &tmp->enc);
      | ^~~~~~~~~~~
cc1: all warnings being treated as errors
```

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines
