### PR TITLE
res/stasis/control.c: include signal.h

### PR DESCRIPTION
**Pull request by ffontaine**
Include `signal.h` to avoid the following build failure with uclibc-ng raised since https://github.com/asterisk/asterisk/commit/2694792e13c7f3ab1911c4a69fba0df32c544177:

```
stasis/control.c: In function 'exec_command_on_condition': stasis/control.c:313:3: warning: implicit declaration of function 'pthread_kill'; did you mean 'pthread_yield'? [-Wimplicit-function-declaration]
  313 |   pthread_kill(control->control_thread, SIGURG);
      |   ^~~~~~~~~~~~
      |   pthread_yield
stasis/control.c:313:41: error: 'SIGURG' undeclared (first use in this function)
  313 |   pthread_kill(control->control_thread, SIGURG);
      |                                         ^~~~~~
```

Fixes:  #729

### CODE REVIEW

**Review by gtjoseph — CHANGES_REQUESTED** [review]
Things to do...

- [x] Remove the 'Fixes" line since it doesn't reference a GitHub issue.
- [x] If not a trivial change (typo, documentation correction, etc) open an issue describing the problem.
- [x] Make sure the PR description and commit message reference the issue. See [Commit Messages](https://docs.asterisk.org/Development/Policies-and-Procedures/Commit-Messages/)
- [x] If you still need the 'Signed-off-by' header, it must come before any "special" headers like Fixes, Resolves, UserNote, UpgradeNote.  See [Commit Messages](https://docs.asterisk.org/Development/Policies-and-Procedures/Commit-Messages/)
- [x] Add the appropriate "cherry-pick" PR comment. See [Code Contribution](https://docs.asterisk.org/Development/Policies-and-Procedures/Code-Contribution/)

See:
https://docs.asterisk.org/Development/Policies-and-Procedures/Commit-Messages/
https://docs.asterisk.org/Development/Policies-and-Procedures/Coding-Guidelines/
https://docs.asterisk.org/Development/Policies-and-Procedures/Code-Contribution/

**Comment by gtjoseph** [comment]
@ffontaine For future reference, the cherry-pick lines have to be in a separate comment, not in the PR description.

**Comment by gtjoseph** [comment]
cherry-pick-to: 18
cherry-pick-to: 20
cherry-pick-to: 21

**Review by gtjoseph — APPROVED** [review]
